---
- hosts: unifi_pi
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - name: Remove old UniFi package
      import_tasks: remove_unifi.yml
    - name: Install Unifi Controller
      import_tasks: update_unifi_controller.yml
...